---
version: 2
multicolumn: false
web-width: 500px
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/86022/articles/160859/master/file/figures/Neighboring_countries_graph_in_russian_according_to_Wikidata/Neighboring_countries_graph_in_russian_according_to_Wikidata.png"
    path: figures/Neighboring_countries_graph_in_russian_according_to_Wikidata/Neighboring_countries_graph_in_russian_according_to_Wikidata.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
